### ISSUE TITLE
Function and KEGG species id not working

### ISSUE THREAD

**Issue by Fuad59** [lgeistlinger/EnrichmentBrowser#39]
showAvailableSpecies()....
### Error in showAvailableSpecies(db = "enrichr") : 
**could not find function "showAvailableSpecies"**
Please tell me the package name for this function, if it needs another package to work with Enrichment Browser.
Ref: http://bioconductor.org/packages/release/bioc/manuals/EnrichmentBrowser/man/EnrichmentBrowser.pdf, page:18.
  .............................
  My interest species has a **4 letter code in KEGG species list** aplc (_Acanthaster planci_) but in this package only 3 letter code is working. Please suggest any alternatives.
  Ref: https://www.genome.jp/kegg/catalog/org_list.html  (Echinoderms)
  Thank you.

**Comment by lgeistlinger** [comment]
Can you provide the output of typing 

```
sessionInfo()
```

into your R session?

**Comment by Fuad59** [comment]
> Can you provide the output of typing
> 
> ```
> sessionInfo()
> ```
> 
> into your R session?

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] EnrichmentBrowser_2.18.2    graph_1.66.0                SummarizedExperiment_1.18.2
 [4] DelayedArray_0.14.1         matrixStats_0.58.0          Biobase_2.48.0             
 [7] GenomicRanges_1.40.0        GenomeInfoDb_1.24.2         IRanges_2.22.2             
[10] S4Vectors_0.26.1            BiocGenerics_0.34.0        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6             pillar_1.4.7           dbplyr_2.1.0          
 [4] compiler_4.0.2         XVector_0.28.0         bitops_1.0-6          
 [7] tools_4.0.2            zlibbioc_1.34.0        bit_4.0.4             
[10] tibble_3.0.6           lifecycle_0.2.0        annotate_1.66.0       
[13] RSQLite_2.2.3          memoise_2.0.0          BiocFileCache_1.12.1  
[16] lattice_0.20-41        pkgconfig_2.0.3        rlang_0.4.10          
[19] Matrix_1.2-18          KEGGgraph_1.48.0       DBI_1.1.1             
[22] curl_4.3               fastmap_1.1.0          GenomeInfoDbData_1.2.3
[25] withr_2.4.1            httr_1.4.2             dplyr_1.0.4           
[28] generics_0.1.0         vctrs_0.3.6            rappdirs_0.3.3        
[31] tidyselect_1.1.0       bit64_4.0.5            grid_4.0.2            
[34] glue_1.4.2             GSEABase_1.50.1        R6_2.5.0              
[37] AnnotationDbi_1.50.3   XML_3.99-0.5           purrr_0.3.4           
[40] magrittr_2.0.1         blob_1.2.1             ellipsis_0.3.1        
[43] assertthat_0.2.1       xtable_1.8-4           RCurl_1.98-1.2        
[46] cachem_1.0.3           crayon_1.4.1

**Comment by lgeistlinger** [comment]
You are sitting on an outdated version of EnrichmentBrowser (v2.18.2). Make sure to have the release version EnrichmentBrowser (v2.20.7) installed. Follow the installation instructions under https://bioconductor.org/packages/EnrichmentBrowser for that.

**Comment by lgeistlinger** [comment]
Note that the installation of EnrichmentBrowser (v2.20.7) will allow you to solve the first part of your question, ie to use the `showAvailableSpecies` function. For example, to inspect which species are available for KEGG:

```
library(EnrichmentBrowser)
> showAvailableSpecies(db = "kegg")
DataFrame with 7002 rows and 3 columns
            kegg                    tax                 common
     <character>            <character>            <character>
1            hsa           Homo sapiens                  human
2            ptr        Pan troglodytes             chimpanzee
3            pps           Pan paniscus                 bonobo
4            ggo Gorilla gorilla gori.. western lowland gori..
5            pon           Pongo abelii     Sumatran orangutan
...          ...                    ...                    ...
6998         miy Candidatus Micrarcha..                       
6999        loki Lokiarchaeum sp. GC1..                       
7000        psyt Candidatus Prometheo..                       
7001         agw   Archaeon GW2011_AR10                       
7002         arg   Archaeon GW2011_AR20
```

The second part of your question required indeed an update to the EnrichmentBrowser, which I just pushed to github.
You can install the new version (EnrichmentBrowser_2.21.10) directly from github via:

```
BiocManager::install("remotes")
BiocManager::install("lgeistlinger/EnrichmentBrowser")
```

Once you have that start a fresh R session and do:
```
library(EnrichmentBrowser)
> gs <- getGenesets(org = "aplc", db = "kegg")
> gs[1:3]
$`aplc00010_Glycolysis_/_Gluconeogenesis`
 [1] "110973933" "110974400" "110975296" "110976729" "110976983" "110977508"
 [7] "110977545" "110978965" "110979053" "110979122" "110979578" "110979809"
[13] "110979928" "110980089" "110980090" "110980122" "110980365" "110980434"
[19] "110981183" "110981255" "110981579" "110982882" "110983098" "110983680"
[25] "110985012" "110985127" "110986929" "110987005" "110987124" "110987278"
[31] "110987489" "110987576" "110987693" "110987779" "110987921" "110988023"
[37] "110988120" "110988280" "110989373" "110990349" "110991022" "110991213"

$`aplc00020_Citrate_cycle_(TCA_cycle)`
 [1] "110973822" "110974097" "110974400" "110975163" "110975296" "110976738"
 [7] "110978102" "110979126" "110980089" "110980090" "110980522" "110980666"
[13] "110982044" "110982138" "110982381" "110982591" "110983617" "110983680"
[19] "110984224" "110984266" "110984525" "110986141" "110986325" "110986692"
[25] "110986840" "110986929" "110987051" "110987889" "110988741" "110990396"

$aplc00030_Pentose_phosphate_pathway
 [1] "110976881" "110976983" "110977080" "110978144" "110978779" "110978782"
 [7] "110979578" "110979809" "110980122" "110983992" "110985618" "110985630"
[13] "110986468" "110987124" "110987921" "110988397" "110988461" "110988634"
[19] "110989373" "110989775" "110989840" "110990171" "110991049"
```

to obtain KEGG gene sets for you species of interest.

**Comment by Fuad59** [comment]
> You are sitting on an outdated version of EnrichmentBrowser (v2.18.2). Make sure to have the release version EnrichmentBrowser (v2.20.7) installed. Follow the installation instructions under https://bioconductor.org/packages/EnrichmentBrowser for that.

Thank you very much. The 1st problem is solved.

**Comment by Fuad59** [comment]
> Note that the installation of EnrichmentBrowser (v2.20.7) will allow you to solve the first part of your question, ie to use the `showAvailableSpecies` function. For example, to inspect which species are available for KEGG:
> 
> ```
> library(EnrichmentBrowser)
> > showAvailableSpecies(db = "kegg")
> DataFrame with 7002 rows and 3 columns
>             kegg                    tax                 common
>      <character>            <character>            <character>
> 1            hsa           Homo sapiens                  human
> 2            ptr        Pan troglodytes             chimpanzee
> 3            pps           Pan paniscus                 bonobo
> 4            ggo Gorilla gorilla gori.. western lowland gori..
> 5            pon           Pongo abelii     Sumatran orangutan
> ...          ...                    ...                    ...
> 6998         miy Candidatus Micrarcha..                       
> 6999        loki Lokiarchaeum sp. GC1..                       
> 7000        psyt Candidatus Prometheo..                       
> 7001         agw   Archaeon GW2011_AR10                       
> 7002         arg   Archaeon GW2011_AR20
> ```
> 
> The second part of your question required indeed an update to the EnrichmentBrowser, which I just pushed to github.
> You can install the new version (EnrichmentBrowser_2.21.10) directly from github via:
> 
> ```
> BiocManager::install("remotes")
> BiocManager::install("lgeistlinger/EnrichmentBrowser")
> ```
> 
> Once you have that start a fresh R session and do:
> 
> ```
> library(EnrichmentBrowser)
> > gs <- getGenesets(org = "aplc", db = "kegg")
> > gs[1:3]
> $`aplc00010_Glycolysis_/_Gluconeogenesis`
>  [1] "110973933" "110974400" "110975296" "110976729" "110976983" "110977508"
>  [7] "110977545" "110978965" "110979053" "110979122" "110979578" "110979809"
> [13] "110979928" "110980089" "110980090" "110980122" "110980365" "110980434"
> [19] "110981183" "110981255" "110981579" "110982882" "110983098" "110983680"
> [25] "110985012" "110985127" "110986929" "110987005" "110987124" "110987278"
> [31] "110987489" "110987576" "110987693" "110987779" "110987921" "110988023"
> [37] "110988120" "110988280" "110989373" "110990349" "110991022" "110991213"
> 
> $`aplc00020_Citrate_cycle_(TCA_cycle)`
>  [1] "110973822" "110974097" "110974400" "110975163" "110975296" "110976738"
>  [7] "110978102" "110979126" "110980089" "110980090" "110980522" "110980666"
> [13] "110982044" "110982138" "110982381" "110982591" "110983617" "110983680"
> [19] "110984224" "110984266" "110984525" "110986141" "110986325" "110986692"
> [25] "110986840" "110986929" "110987051" "110987889" "110988741" "110990396"
> 
> $aplc00030_Pentose_phosphate_pathway
>  [1] "110976881" "110976983" "110977080" "110978144" "110978779" "110978782"
>  [7] "110979578" "110979809" "110980122" "110983992" "110985618" "110985630"
> [13] "110986468" "110987124" "110987921" "110988397" "110988461" "110988634"
> [19] "110989373" "110989775" "110989840" "110990171" "110991049"
> ```
> 
> to obtain KEGG gene sets for you species of interest.

...............................................................................................................
...............................................................................................................
**### Sorry still having problem to install EnrichmentBrowser 2.21.10**
> BiocManager::install("lgeistlinger/EnrichmentBrowser")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing github package(s) 'lgeistlinger/EnrichmentBrowser'
Downloading GitHub repo lgeistlinger/EnrichmentBrowser@HEAD
√  checking for file 'C:\Users\forest\AppData\Local\Temp\Rtmp0cQFrU\remotes57f0fd130e1\lgeistlinger-EnrichmentBrowser-339bc56/DESCRIPTION' ...
-  preparing 'EnrichmentBrowser': (1.1s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'EnrichmentBrowser_2.21.10.tar.gz'
   
* installing *source* package 'EnrichmentBrowser' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'matrixStats' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'EnrichmentBrowser'
* removing 'C:/Users/forest/Documents/R/win-library/4.0/EnrichmentBrowser'
Error: Failed to install 'EnrichmentBrowser' from GitHub:
  (converted from warning) installation of package ‘C:/Users/forest/AppData/Local/Temp/Rtmp0cQFrU/file57f036185fb6/EnrichmentBrowser_2.21.10.tar.gz’ had non-zero exit status
>

**Comment by lgeistlinger** [comment]
I think you have two options here:

1. set `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS"=TRUE)` before calling `BiocManager::install("lgeistlinger/EnrichmentBrowser")`
2. Upgrade to the latest version of R (4.0.3, https://cran.r-project.org/) and start from the beginning

Option 1 might get you fast to try things out, Option 2 you will need to do eventually as R will keep you bugging about the fact that a newer version of R is available.

**Comment by Fuad59** [comment]
> I think you have two options here:
> 
> 1. set `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS"=TRUE)` before calling `BiocManager::install("lgeistlinger/EnrichmentBrowser")`
> 2. Upgrade to the latest version of R (4.0.3, https://cran.r-project.org/) and start from the beginning
> 
> Option 1 might get you fast to try things out, Option 2 you will need to do eventually as R will keep you bugging about the fact that a newer version of R is available.

Option 1 worked well. Thank you very much for your feedback.
